music_directory "~/Music"

pid_file			"$XDG_RUNTIME_DIR/mpd/mpd.pid"
state_file			"$XDG_RUNTIME_DIR/mpd/state"
sticker_file		"$XDG_CACHE_HOME/sticker.sql"

playlist_directory		"~/.local/share/mpd/playlists"


db_file			    "~/.local/share/mpd/database"

restore_paused "yes"

auto_update	"yes"
auto_update_depth	"no"

port "6600"

audio_output {
	type		"pipewire"
	name		"pipewire output"
}

log_file "~/.local/share/mpd/log"
state_file "~/.local/share/mpd/state"
sticker_file "~/.local/share/mpd/sticker.sql"

follow_outside_symlinks "yes"
follow_inside_symlinks "yes"


bind_to_address "~/.local/share/mpd/socket"
bind_to_address "127.0.0.1"