# Core Colors
background            #1a120e
foreground            #f1dfd8
selection_foreground  #ffb695
selection_background  #542105
cursor                #ffb695
cursor_text_color     #1a120e

# Regular Colors
color0  #1a120e
color1  #ffb4ab
color2  #ffb695
color3  #d1c88f
color4  #ffdbcc
color5  #ffdbcc
color6  #e6bead
color7  #f1dfd8

# Bright Colors
color8  #423732
color9  #ffb4ab
color10 #ffb695
color11 #d1c88f
color12 #ffdbcc
color13 #ffdbcc 
color14 #e6bead
color15 #f1dfd8