# Core Colors
background            #121318
foreground            #e3e2e9
selection_foreground  #b3c5ff
selection_background  #192e60
cursor                #b3c5ff
cursor_text_color     #121318

# Regular Colors
color0  #121318
color1  #ffb4ab
color2  #b3c5ff
color3  #e1bbdc
color4  #dae1ff
color5  #dde2f9
color6  #c1c6dd
color7  #e3e2e9

# Bright Colors
color8  #38393f
color9  #ffb4ab
color10 #b3c5ff
color11 #e1bbdc
color12 #dae1ff
color13 #dde2f9 
color14 #c1c6dd
color15 #e3e2e9