# Core Colors
background            #17130b
foreground            #ece1d4
selection_foreground  #efbf6d
selection_background  #422c00
cursor                #efbf6d
cursor_text_color     #17130b

# Regular Colors
color0  #17130b
color1  #ffb4ab
color2  #efbf6d
color3  #b4cea5
color4  #ffdeaa
color5  #f8dfbb
color6  #dbc3a1
color7  #ece1d4

# Bright Colors
color8  #3f382f
color9  #ffb4ab
color10 #efbf6d
color11 #b4cea5
color12 #ffdeaa
color13 #f8dfbb 
color14 #dbc3a1
color15 #ece1d4